### PR TITLE
Ignoring Linux for now

### PR DESCRIPTION
**Pull request by tomvanmele**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
why u no like linux? 🤷‍♂️😉

**Comment by tomvanmele** [comment]
for whatever reason it fails on linux (even though everything worked fine at the PR stage). there seems to be a bug in some kind of "pinning" thing as far as i can tell from the gitter conversation...

```
ValueError: Variant configuration errors in /home/conda/feedstock_root/.ci_support/linux_64_python3.8.____cpython.yaml:
 zip fields in zip_key group ('cdt_name', 'docker_image') are not all the same length
```

**Comment by gonzalocasas** [comment]
got it! thx. do you refer to the gitter conv that can be found via google (from Nov 2019)?

**Comment by tomvanmele** [comment]
no stuff from yesterday...

**Pull request merged**
